# Generated by Django 3.2.5 on 2021-08-27 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5)),
                ('balance', models.IntegerField()),
                ('weekly_pickup_day', models.CharField(max_length=10)),
                ('one_time_pickup', models.DateField()),
                ('suspend_start', models.DateField(null=True)),
                ('suspend_end', models.DateField(null=True)),
                ('suspend_status', models.BooleanField(null=True)),
                ('pickup_status', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
